### ISSUE TITLE
什么是Fluid dynamics grounding？

### ISSUE THREAD

**Issue by sleeplessai** [syguan96/NeuroFluid#7]
想请问一下论文中提到的Fluid dynamics grounding是什么任务？中文如何翻译？
FDG的必要和需求在哪里？

**Comment by syguan96** [comment]
你好，推荐参考这篇推送：https://news.sjtu.edu.cn/jdzh/20220602/171985.html

**Comment by sleeplessai** [comment]
感谢分享，反演一词解决了我诸多困惑。

**Comment by sleeplessai** [comment]
@syguan96 如果要follow这项新任务，您推荐是自己生成数据还是使用你们提供的数据集呢？

**Comment by syguan96** [comment]
我们在readme里有视频讲如何生成数据。我觉得还是先follow这个吧

From my phone

**Comment by sleeplessai** [comment]
@syguan96 
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 192.00 MiB (GPU 0; 10.75 GiB total capacity; 9.50 GiB already allocated; 99.31 MiB free; 9.60 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

在复现时候出现了问题，用的是configs/warmup.yaml中的配置。
请问你们实验时GPU的显存占用是多少？

**Comment by syguan96** [comment]
我们用的是一张3090，我印象中显存占用是20G左右
